name: Build and Push to GitHub Container Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Преобразование имен в нижний регистр
        uses: ./convert-to-lowercase
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          docker_user: triksdev

      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          echo ${env.IMAGE_NAME_GHCR}
          echo ${env.IMAGE_NAME_DOCKER}

      

